"dodstudio_ui/Demos.res"
{
	"SearchLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"SearchLabel"
		"xpos"		"8"
		"ypos"		"6"
		"wide"		"48"
		"tall"		"24"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"Search"
		"textAlignment"		"west"
		"helptext"		"Type part of a demo name or map: the list shows only the demos that match."
	}
	"DemoFilter"
	{
		"ControlName"		"TextEntry"
		"fieldName"		"DemoFilter"
		"xpos"		"60"
		"ypos"		"6"
		"wide"		"170"
		"tall"		"24"
		"visible"		"1"
		"enabled"		"1"
		"helptext"		"Part of a demo name or map, or several words: every word has to match."
	}
	"MapLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"MapLabel"
		"xpos"		"238"
		"ypos"		"6"
		"wide"		"32"
		"tall"		"24"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"Map"
		"textAlignment"		"west"
		"helptext"		"Only demos on this map."
	}
	"MapFilter"
	{
		"ControlName"		"TextEntry"
		"fieldName"		"MapFilter"
		"xpos"		"274"
		"ypos"		"6"
		"wide"		"110"
		"tall"		"24"
		"visible"		"1"
		"enabled"		"1"
		"helptext"		"Part of a map name, like anzio or flash."
	}
	"DaysLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"DaysLabel"
		"xpos"		"392"
		"ypos"		"6"
		"wide"		"74"
		"tall"		"24"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"Days old <"
		"textAlignment"		"west"
		"helptext"		"Only demos newer than this many days."
	}
	"DaysFilter"
	{
		"ControlName"		"TextEntry"
		"fieldName"		"DaysFilter"
		"xpos"		"470"
		"ypos"		"6"
		"wide"		"50"
		"tall"		"24"
		"visible"		"1"
		"enabled"		"1"
		"helptext"		"A number of days. Empty shows every age."
	}
	"ShowHltv"
	{
		"ControlName"		"CheckButton"
		"fieldName"		"ShowHltv"
		"xpos"		"8"
		"ypos"		"34"
		"wide"		"70"
		"tall"		"22"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"HLTV"
		"textAlignment"		"west"
		"helptext"		"Show demos an HLTV proxy recorded."
	}
	"ShowPov"
	{
		"ControlName"		"CheckButton"
		"fieldName"		"ShowPov"
		"xpos"		"80"
		"ypos"		"34"
		"wide"		"70"
		"tall"		"22"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"POV"
		"textAlignment"		"west"
		"helptext"		"Show demos a player recorded."
	}
	"PlayerLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"PlayerLabel"
		"xpos"		"158"
		"ypos"		"34"
		"wide"		"44"
		"tall"		"22"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"Player"
		"textAlignment"		"west"
		"helptext"		"Only demos this player is in: part of a name or a SteamID. Only demos analysed so far are searched."
	}
	"PlayerFilter"
	{
		"ControlName"		"TextEntry"
		"fieldName"		"PlayerFilter"
		"xpos"		"206"
		"ypos"		"34"
		"wide"		"170"
		"tall"		"22"
		"visible"		"1"
		"enabled"		"1"
		"helptext"		"Part of a player name or SteamID. Only demos Studio or the Highlights tab analysed are searched."
	}
	"PlayerRecorded"
	{
		"ControlName"		"CheckButton"
		"fieldName"		"PlayerRecorded"
		"xpos"		"384"
		"ypos"		"34"
		"wide"		"136"
		"tall"		"22"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"They recorded it"
		"textAlignment"		"west"
		"helptext"		"Only POV demos this player recorded."
	}
	"DemoListSlot"
	{
		"ControlName"		"Label"
		"fieldName"		"DemoListSlot"
		"xpos"		"8"
		"ypos"		"60"
		"wide"		"520"
		"tall"		"142"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		""
		"textAlignment"		"west"
		"helptext"		"Your demos. Double-click one to play it."
	}
	"DemoLoadSlot"
	{
		"ControlName"		"Label"
		"fieldName"		"DemoLoadSlot"
		"xpos"		"8"
		"ypos"		"208"
		"wide"		"96"
		"tall"		"24"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		""
		"textAlignment"		"west"
		"helptext"		"Play the selected demo."
	}
	"Hint"
	{
		"ControlName"		"Label"
		"fieldName"		"Hint"
		"xpos"		"112"
		"ypos"		"208"
		"wide"		"416"
		"tall"		"24"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"Double-click a demo, or pick one and Load. Folders: dodstudio_demo_list_folders 1"
		"textAlignment"		"west"
	}
	"PlayerNote"
	{
		"ControlName"		"Label"
		"fieldName"		"PlayerNote"
		"xpos"		"112"
		"ypos"		"208"
		"wide"		"416"
		"tall"		"24"
		"visible"		"0"
		"enabled"		"1"
		"labelText"		""
		"textAlignment"		"west"
		"helptext"		"Open a demo in Studio's Demo Analyzer, or its Highlights tab here, to add it to the Player search."
	}
}
