"dodstudio_ui/Demos.res"
{
	"SearchLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"SearchLabel"
		"xpos"		"8"
		"ypos"		"6"
		"wide"		"48"
		"tall"		"24"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"Search"
		"textAlignment"		"west"
		"tooltiptext"		"Type part of a demo name: the list shows only the demos that match."
	}
	"DemoFilter"
	{
		"ControlName"		"TextEntry"
		"fieldName"		"DemoFilter"
		"xpos"		"60"
		"ypos"		"6"
		"wide"		"260"
		"tall"		"24"
		"visible"		"1"
		"enabled"		"1"
		"tooltiptext"		"Type part of a demo name, or several words: every word has to match."
	}
	"DemoListSlot"
	{
		"ControlName"		"Label"
		"fieldName"		"DemoListSlot"
		"xpos"		"8"
		"ypos"		"36"
		"wide"		"520"
		"tall"		"166"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		""
		"textAlignment"		"west"
		"tooltiptext"		"Your demos. Double-click one to play it."
	}
	"DemoLoadSlot"
	{
		"ControlName"		"Label"
		"fieldName"		"DemoLoadSlot"
		"xpos"		"8"
		"ypos"		"208"
		"wide"		"96"
		"tall"		"24"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		""
		"textAlignment"		"west"
		"tooltiptext"		"Play the selected demo."
	}
	"Hint"
	{
		"ControlName"		"Label"
		"fieldName"		"Hint"
		"xpos"		"112"
		"ypos"		"208"
		"wide"		"416"
		"tall"		"24"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"Double-click a demo, or pick one and Load. Folders: dodstudio_demo_list_folders 1"
		"textAlignment"		"west"
	}
}
