"dodstudio_ui/DodStudioPanel.res"
{
	"DodStudioPanel"
	{
		"ControlName"		"Frame"
		"fieldName"		"DodStudioPanel"
		"xpos"		"120"
		"ypos"		"80"
		"wide"		"520"
		"tall"		"200"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"title"		"DoD Studio"
	}
	"tab_playback"
	{
		"ControlName"		"Button"
		"fieldName"		"tab_playback"
		"xpos"		"12"
		"ypos"		"32"
		"wide"		"96"
		"tall"		"24"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"Playback"
		"textAlignment"		"center"
		"Command"		"tab playback"
	}
	"tab_demos"
	{
		"ControlName"		"Button"
		"fieldName"		"tab_demos"
		"xpos"		"112"
		"ypos"		"32"
		"wide"		"96"
		"tall"		"24"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"Demos"
		"textAlignment"		"center"
		"Command"		"tab demos"
	}
	"tab_studio"
	{
		"ControlName"		"Button"
		"fieldName"		"tab_studio"
		"xpos"		"212"
		"ypos"		"32"
		"wide"		"96"
		"tall"		"24"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"Studio"
		"textAlignment"		"center"
		"Command"		"tab studio"
	}
	"playback_start"
	{
		"ControlName"		"Button"
		"fieldName"		"playback_start"
		"xpos"		"12"
		"ypos"		"72"
		"wide"		"40"
		"tall"		"24"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"|<"
		"textAlignment"		"center"
		"Command"		"start"
	}
	"playback_slower"
	{
		"ControlName"		"Button"
		"fieldName"		"playback_slower"
		"xpos"		"56"
		"ypos"		"72"
		"wide"		"40"
		"tall"		"24"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"<<"
		"textAlignment"		"center"
		"Command"		"slower"
	}
	"playback_stepb"
	{
		"ControlName"		"Button"
		"fieldName"		"playback_stepb"
		"xpos"		"100"
		"ypos"		"72"
		"wide"		"40"
		"tall"		"24"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"<|"
		"textAlignment"		"center"
		"Command"		"stepb"
	}
	"playback_pause"
	{
		"ControlName"		"Button"
		"fieldName"		"playback_pause"
		"xpos"		"144"
		"ypos"		"72"
		"wide"		"40"
		"tall"		"24"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"||"
		"textAlignment"		"center"
		"Command"		"pause"
	}
	"playback_play"
	{
		"ControlName"		"Button"
		"fieldName"		"playback_play"
		"xpos"		"188"
		"ypos"		"72"
		"wide"		"40"
		"tall"		"24"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		">"
		"textAlignment"		"center"
		"Command"		"play"
	}
	"playback_stepf"
	{
		"ControlName"		"Button"
		"fieldName"		"playback_stepf"
		"xpos"		"232"
		"ypos"		"72"
		"wide"		"40"
		"tall"		"24"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"|>"
		"textAlignment"		"center"
		"Command"		"stepf"
	}
	"playback_faster"
	{
		"ControlName"		"Button"
		"fieldName"		"playback_faster"
		"xpos"		"276"
		"ypos"		"72"
		"wide"		"40"
		"tall"		"24"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		">>"
		"textAlignment"		"center"
		"Command"		"faster"
	}
	"playback_end"
	{
		"ControlName"		"Button"
		"fieldName"		"playback_end"
		"xpos"		"320"
		"ypos"		"72"
		"wide"		"40"
		"tall"		"24"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		">|"
		"textAlignment"		"center"
		"Command"		"end"
	}
	"playback_stop"
	{
		"ControlName"		"Button"
		"fieldName"		"playback_stop"
		"xpos"		"364"
		"ypos"		"72"
		"wide"		"56"
		"tall"		"24"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"Stop"
		"textAlignment"		"center"
		"Command"		"stop"
	}
	"playback_load"
	{
		"ControlName"		"Button"
		"fieldName"		"playback_load"
		"xpos"		"12"
		"ypos"		"108"
		"wide"		"120"
		"tall"		"24"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"Load demo..."
		"textAlignment"		"center"
		"Command"		"load"
	}
	"playback_events"
	{
		"ControlName"		"Button"
		"fieldName"		"playback_events"
		"xpos"		"140"
		"ypos"		"108"
		"wide"		"120"
		"tall"		"24"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"Events..."
		"textAlignment"		"center"
		"Command"		"events"
	}
	"playback_hint"
	{
		"ControlName"		"Label"
		"fieldName"		"playback_hint"
		"xpos"		"12"
		"ypos"		"150"
		"wide"		"490"
		"tall"		"24"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"Drives the demo player: start a demo with viewdemo first."
		"textAlignment"		"west"
	}
	"demos_load"
	{
		"ControlName"		"Button"
		"fieldName"		"demos_load"
		"xpos"		"12"
		"ypos"		"72"
		"wide"		"160"
		"tall"		"24"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"Open Load Demo..."
		"textAlignment"		"center"
		"Command"		"load"
	}
	"demos_hint"
	{
		"ControlName"		"Label"
		"fieldName"		"demos_hint"
		"xpos"		"12"
		"ypos"		"108"
		"wide"		"490"
		"tall"		"24"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"Demo list coming here. For folders now: dodstudio_demo_list_folders 1"
		"textAlignment"		"west"
	}
	"studio_status"
	{
		"ControlName"		"Button"
		"fieldName"		"studio_status"
		"xpos"		"12"
		"ypos"		"72"
		"wide"		"160"
		"tall"		"24"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"Hook status (console)"
		"textAlignment"		"center"
		"Command"		"engine dodstudio_debug_status"
	}
	"studio_hint"
	{
		"ControlName"		"Label"
		"fieldName"		"studio_hint"
		"xpos"		"12"
		"ypos"		"108"
		"wide"		"490"
		"tall"		"24"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"Edit this window: Ctrl+Shift+Alt+B on it, then Save."
		"textAlignment"		"west"
	}
}
