"dodstudio_ui/Killstreaks.res"
{
	"StreakStatus"
	{
		"ControlName"		"Label"
		"fieldName"		"StreakStatus"
		"xpos"		"8"
		"ypos"		"6"
		"wide"		"520"
		"tall"		"20"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		""
		"textAlignment"		"west"
		"tooltiptext"		"The demo playing now, and how far along finding its killstreaks is."
	}
	"StreakProgress"
	{
		"ControlName"		"ProgressBar"
		"fieldName"		"StreakProgress"
		"xpos"		"8"
		"ypos"		"30"
		"wide"		"520"
		"tall"		"14"
		"visible"		"0"
		"enabled"		"1"
		"tooltiptext"		"Reading the demo. Studio's own analysis is reused when Studio already read it."
	}
	"StreakListSlot"
	{
		"ControlName"		"Label"
		"fieldName"		"StreakListSlot"
		"xpos"		"8"
		"ypos"		"50"
		"wide"		"520"
		"tall"		"152"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		""
		"textAlignment"		"west"
		"tooltiptext"		"Every streak of 2 or more kills in one life. Click a heading to sort. Double-click a streak to jump to it."
	}
	"StreakGoSlot"
	{
		"ControlName"		"Label"
		"fieldName"		"StreakGoSlot"
		"xpos"		"8"
		"ypos"		"208"
		"wide"		"96"
		"tall"		"24"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		""
		"textAlignment"		"west"
		"tooltiptext"		"Jump to 5 seconds before the selected streak's first kill."
	}
	"Hint"
	{
		"ControlName"		"Label"
		"fieldName"		"Hint"
		"xpos"		"112"
		"ypos"		"208"
		"wide"		"416"
		"tall"		"24"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"Double-click a streak, or pick one and Go. Play the demo with viewdemo."
		"textAlignment"		"west"
	}
}
