"dodstudio_ui/Killstreaks.res"
{
	"StreakStatus"
	{
		"ControlName"		"Label"
		"fieldName"		"StreakStatus"
		"xpos"		"8"
		"ypos"		"6"
		"wide"		"520"
		"tall"		"20"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		""
		"textAlignment"		"west"
		"tooltiptext"		"The demo playing now, and how far along finding its killstreaks is."
	}
	"StreakProgress"
	{
		"ControlName"		"ProgressBar"
		"fieldName"		"StreakProgress"
		"xpos"		"8"
		"ypos"		"30"
		"wide"		"520"
		"tall"		"14"
		"visible"		"0"
		"enabled"		"1"
		"tooltiptext"		"Reading the demo. Studio's own analysis is reused when Studio already read it."
	}
	"StreakListSlot"
	{
		"ControlName"		"Label"
		"fieldName"		"StreakListSlot"
		"xpos"		"8"
		"ypos"		"50"
		"wide"		"520"
		"tall"		"152"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		""
		"textAlignment"		"west"
		"tooltiptext"		"Every life with a kill: who, how many, with what, and when. Click a heading to sort. Double-click one to jump to it."
	}
	"StreakGoSlot"
	{
		"ControlName"		"Label"
		"fieldName"		"StreakGoSlot"
		"xpos"		"8"
		"ypos"		"208"
		"wide"		"96"
		"tall"		"24"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		""
		"textAlignment"		"west"
		"tooltiptext"		"Jump to 5 seconds before the selected streak's first kill."
	}
	"Hint"
	{
		"ControlName"		"Label"
		"fieldName"		"Hint"
		"xpos"		"112"
		"ypos"		"208"
		"wide"		"416"
		"tall"		"24"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"Double-click a streak, or pick one and Go. Play the demo with viewdemo."
		"textAlignment"		"west"
	}
	"StreakPlayerLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"StreakPlayerLabel"
		"xpos"		"8"
		"ypos"		"27"
		"wide"		"44"
		"tall"		"20"
		"visible"		"0"
		"enabled"		"1"
		"labelText"		"Player"
		"textAlignment"		"west"
		"tooltiptext"		"Only this player's streaks: part of a name, or several words."
	}
	"StreakPlayer"
	{
		"ControlName"		"TextEntry"
		"fieldName"		"StreakPlayer"
		"xpos"		"56"
		"ypos"		"27"
		"wide"		"180"
		"tall"		"20"
		"visible"		"0"
		"enabled"		"1"
		"tooltiptext"		"Only this player's streaks: part of a name, or several words."
	}
	"StreakMinKillsLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"StreakMinKillsLabel"
		"xpos"		"248"
		"ypos"		"27"
		"wide"		"56"
		"tall"		"20"
		"visible"		"0"
		"enabled"		"1"
		"labelText"		"Min kills"
		"textAlignment"		"west"
		"tooltiptext"		"Only highlights with at least this many kills. Empty shows every one."
	}
	"StreakMinKills"
	{
		"ControlName"		"TextEntry"
		"fieldName"		"StreakMinKills"
		"xpos"		"308"
		"ypos"		"27"
		"wide"		"40"
		"tall"		"20"
		"visible"		"0"
		"enabled"		"1"
		"tooltiptext"		"Only highlights with at least this many kills. Empty shows every one."
	}
}
