"dodstudio_ui/Playback.res"
{
	"TimeSliderSlot"
	{
		"ControlName"		"Label"
		"fieldName"		"TimeSliderSlot"
		"xpos"		"8"
		"ypos"		"6"
		"wide"		"488"
		"tall"		"28"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		""
		"textAlignment"		"west"
	}
	"startButton"
	{
		"ControlName"		"Button"
		"fieldName"		"startButton"
		"xpos"		"8"
		"ypos"		"40"
		"wide"		"40"
		"tall"		"24"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"|<"
		"textAlignment"		"center"
		"Command"		"start"
	}
	"slowerButton"
	{
		"ControlName"		"Button"
		"fieldName"		"slowerButton"
		"xpos"		"52"
		"ypos"		"40"
		"wide"		"40"
		"tall"		"24"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"<<"
		"textAlignment"		"center"
		"Command"		"slower"
	}
	"stepbButton"
	{
		"ControlName"		"Button"
		"fieldName"		"stepbButton"
		"xpos"		"96"
		"ypos"		"40"
		"wide"		"40"
		"tall"		"24"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"<|"
		"textAlignment"		"center"
		"Command"		"stepb"
	}
	"pauseButton"
	{
		"ControlName"		"Button"
		"fieldName"		"pauseButton"
		"xpos"		"140"
		"ypos"		"40"
		"wide"		"40"
		"tall"		"24"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"||"
		"textAlignment"		"center"
		"Command"		"pause"
	}
	"playButton"
	{
		"ControlName"		"Button"
		"fieldName"		"playButton"
		"xpos"		"184"
		"ypos"		"40"
		"wide"		"40"
		"tall"		"24"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		">"
		"textAlignment"		"center"
		"Command"		"play"
	}
	"stepfButton"
	{
		"ControlName"		"Button"
		"fieldName"		"stepfButton"
		"xpos"		"228"
		"ypos"		"40"
		"wide"		"40"
		"tall"		"24"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"|>"
		"textAlignment"		"center"
		"Command"		"stepf"
	}
	"fasterButton"
	{
		"ControlName"		"Button"
		"fieldName"		"fasterButton"
		"xpos"		"272"
		"ypos"		"40"
		"wide"		"40"
		"tall"		"24"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		">>"
		"textAlignment"		"center"
		"Command"		"faster"
	}
	"endButton"
	{
		"ControlName"		"Button"
		"fieldName"		"endButton"
		"xpos"		"316"
		"ypos"		"40"
		"wide"		"40"
		"tall"		"24"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		">|"
		"textAlignment"		"center"
		"Command"		"end"
	}
	"stopButton"
	{
		"ControlName"		"Button"
		"fieldName"		"stopButton"
		"xpos"		"360"
		"ypos"		"40"
		"wide"		"56"
		"tall"		"24"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"Stop"
		"textAlignment"		"center"
		"Command"		"stop"
	}
	"LoadButton"
	{
		"ControlName"		"Button"
		"fieldName"		"LoadButton"
		"xpos"		"8"
		"ypos"		"74"
		"wide"		"120"
		"tall"		"24"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"Load demo..."
		"textAlignment"		"center"
		"Command"		"load"
	}
	"EventsButton"
	{
		"ControlName"		"Button"
		"fieldName"		"EventsButton"
		"xpos"		"136"
		"ypos"		"74"
		"wide"		"120"
		"tall"		"24"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"Events..."
		"textAlignment"		"center"
		"Command"		"events"
	}
	"TimeLabelSlot"
	{
		"ControlName"		"Label"
		"fieldName"		"TimeLabelSlot"
		"xpos"		"270"
		"ypos"		"74"
		"wide"		"226"
		"tall"		"24"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		""
		"textAlignment"		"west"
	}
	"Back10Button"
	{
		"ControlName"		"Button"
		"fieldName"		"Back10Button"
		"xpos"		"8"
		"ypos"		"108"
		"wide"		"52"
		"tall"		"24"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"-10 s"
		"textAlignment"		"center"
		"Command"		"engine dodstudio_seek_by -10"
	}
	"Forward10Button"
	{
		"ControlName"		"Button"
		"fieldName"		"Forward10Button"
		"xpos"		"64"
		"ypos"		"108"
		"wide"		"52"
		"tall"		"24"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"+10 s"
		"textAlignment"		"center"
		"Command"		"engine dodstudio_seek_by 10"
	}
	"HalfSpeedButton"
	{
		"ControlName"		"Button"
		"fieldName"		"HalfSpeedButton"
		"xpos"		"120"
		"ypos"		"108"
		"wide"		"52"
		"tall"		"24"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"x0.5"
		"textAlignment"		"center"
		"Command"		"engine dem_speed 0.5"
	}
	"NormalSpeedButton"
	{
		"ControlName"		"Button"
		"fieldName"		"NormalSpeedButton"
		"xpos"		"176"
		"ypos"		"108"
		"wide"		"52"
		"tall"		"24"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"x1"
		"textAlignment"		"center"
		"Command"		"engine dem_speed 1"
	}
	"DecalsButton"
	{
		"ControlName"		"Button"
		"fieldName"		"DecalsButton"
		"xpos"		"232"
		"ypos"		"108"
		"wide"		"52"
		"tall"		"24"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"Decals"
		"textAlignment"		"center"
		"Command"		"engine dodstudio_clear_decals"
	}
	"GotoLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"GotoLabel"
		"xpos"		"296"
		"ypos"		"108"
		"wide"		"44"
		"tall"		"24"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"Go to"
		"textAlignment"		"east"
	}
	"GotoTime"
	{
		"ControlName"		"TextEntry"
		"fieldName"		"GotoTime"
		"xpos"		"344"
		"ypos"		"108"
		"wide"		"100"
		"tall"		"24"
		"visible"		"1"
		"enabled"		"1"
	}
	"GotoButton"
	{
		"ControlName"		"Button"
		"fieldName"		"GotoButton"
		"xpos"		"448"
		"ypos"		"108"
		"wide"		"48"
		"tall"		"24"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"Go"
		"textAlignment"		"center"
		"Command"		"goto"
	}
	"Hint"
	{
		"ControlName"		"Label"
		"fieldName"		"Hint"
		"xpos"		"8"
		"ypos"		"142"
		"wide"		"488"
		"tall"		"24"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"Go to: 20:33, 20:33:50 or seconds, then Enter. Start a demo with viewdemo first."
		"textAlignment"		"west"
	}
	"EnablePlaybackButton"
	{
		"ControlName"		"Button"
		"fieldName"		"EnablePlaybackButton"
		"xpos"		"8"
		"ypos"		"172"
		"wide"		"400"
		"tall"		"24"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"Show the time and slider here (hides the VCR bar)"
		"textAlignment"		"center"
		"Command"		"engine dodstudio_viewdemo_in_panel 1"
	}
}
