"dodstudio_ui/Playback.res"
{
	"TimeSliderSlot"
	{
		"ControlName"		"Label"
		"fieldName"		"TimeSliderSlot"
		"xpos"		"8"
		"ypos"		"6"
		"wide"		"488"
		"tall"		"28"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		""
		"textAlignment"		"west"
		"tooltiptext"		"Drag to move through the demo."
	}
	"startButton"
	{
		"ControlName"		"Button"
		"fieldName"		"startButton"
		"xpos"		"8"
		"ypos"		"40"
		"wide"		"40"
		"tall"		"24"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"|<"
		"textAlignment"		"center"
		"Command"		"start"
		"tooltiptext"		"Jump to the start of the demo."
	}
	"slowerButton"
	{
		"ControlName"		"Button"
		"fieldName"		"slowerButton"
		"xpos"		"52"
		"ypos"		"40"
		"wide"		"40"
		"tall"		"24"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"<<"
		"textAlignment"		"center"
		"Command"		"slower"
		"tooltiptext"		"Play slower."
	}
	"stepbButton"
	{
		"ControlName"		"Button"
		"fieldName"		"stepbButton"
		"xpos"		"96"
		"ypos"		"40"
		"wide"		"40"
		"tall"		"24"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"<|"
		"textAlignment"		"center"
		"Command"		"stepb"
		"tooltiptext"		"Step back one frame."
	}
	"pauseButton"
	{
		"ControlName"		"Button"
		"fieldName"		"pauseButton"
		"xpos"		"140"
		"ypos"		"40"
		"wide"		"40"
		"tall"		"24"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"||"
		"textAlignment"		"center"
		"Command"		"pause"
		"tooltiptext"		"Pause."
	}
	"playButton"
	{
		"ControlName"		"Button"
		"fieldName"		"playButton"
		"xpos"		"184"
		"ypos"		"40"
		"wide"		"40"
		"tall"		"24"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		">"
		"textAlignment"		"center"
		"Command"		"play"
		"tooltiptext"		"Play."
	}
	"stepfButton"
	{
		"ControlName"		"Button"
		"fieldName"		"stepfButton"
		"xpos"		"228"
		"ypos"		"40"
		"wide"		"40"
		"tall"		"24"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"|>"
		"textAlignment"		"center"
		"Command"		"stepf"
		"tooltiptext"		"Step forward one frame."
	}
	"fasterButton"
	{
		"ControlName"		"Button"
		"fieldName"		"fasterButton"
		"xpos"		"272"
		"ypos"		"40"
		"wide"		"40"
		"tall"		"24"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		">>"
		"textAlignment"		"center"
		"Command"		"faster"
		"tooltiptext"		"Play faster."
	}
	"endButton"
	{
		"ControlName"		"Button"
		"fieldName"		"endButton"
		"xpos"		"316"
		"ypos"		"40"
		"wide"		"40"
		"tall"		"24"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		">|"
		"textAlignment"		"center"
		"Command"		"end"
		"tooltiptext"		"Jump to the end of the demo."
	}
	"stopButton"
	{
		"ControlName"		"Button"
		"fieldName"		"stopButton"
		"xpos"		"360"
		"ypos"		"40"
		"wide"		"56"
		"tall"		"24"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"Stop"
		"textAlignment"		"center"
		"Command"		"stop"
		"tooltiptext"		"Stop the demo."
	}
	"LoadButton"
	{
		"ControlName"		"Button"
		"fieldName"		"LoadButton"
		"xpos"		"8"
		"ypos"		"74"
		"wide"		"120"
		"tall"		"24"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"Load demo..."
		"textAlignment"		"center"
		"Command"		"load"
		"tooltiptext"		"Pick a demo to play (the Demos tab)."
	}
	"EventsButton"
	{
		"ControlName"		"Button"
		"fieldName"		"EventsButton"
		"xpos"		"136"
		"ypos"		"74"
		"wide"		"120"
		"tall"		"24"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"Events..."
		"textAlignment"		"center"
		"Command"		"events"
		"tooltiptext"		"The demo's events list."
	}
	"TimeLabelSlot"
	{
		"ControlName"		"Label"
		"fieldName"		"TimeLabelSlot"
		"xpos"		"270"
		"ypos"		"74"
		"wide"		"226"
		"tall"		"24"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		""
		"textAlignment"		"west"
		"tooltiptext"		"The demo's time, its speed, and whether it is playing."
	}
	"Back10Button"
	{
		"ControlName"		"Button"
		"fieldName"		"Back10Button"
		"xpos"		"8"
		"ypos"		"108"
		"wide"		"52"
		"tall"		"24"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"-10 s"
		"textAlignment"		"center"
		"Command"		"engine dodstudio_seek_by -10"
		"tooltiptext"		"Jump back 10 seconds."
	}
	"Forward10Button"
	{
		"ControlName"		"Button"
		"fieldName"		"Forward10Button"
		"xpos"		"64"
		"ypos"		"108"
		"wide"		"52"
		"tall"		"24"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"+10 s"
		"textAlignment"		"center"
		"Command"		"engine dodstudio_seek_by 10"
		"tooltiptext"		"Jump forward 10 seconds."
	}
	"HalfSpeedButton"
	{
		"ControlName"		"Button"
		"fieldName"		"HalfSpeedButton"
		"xpos"		"120"
		"ypos"		"108"
		"wide"		"52"
		"tall"		"24"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"x0.5"
		"textAlignment"		"center"
		"Command"		"engine dem_speed 0.5"
		"tooltiptext"		"Play at half speed."
	}
	"NormalSpeedButton"
	{
		"ControlName"		"Button"
		"fieldName"		"NormalSpeedButton"
		"xpos"		"176"
		"ypos"		"108"
		"wide"		"52"
		"tall"		"24"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"x1"
		"textAlignment"		"center"
		"Command"		"engine dem_speed 1"
		"tooltiptext"		"Play at normal speed."
	}
	"DecalsButton"
	{
		"ControlName"		"Button"
		"fieldName"		"DecalsButton"
		"xpos"		"232"
		"ypos"		"108"
		"wide"		"52"
		"tall"		"24"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"Decals"
		"textAlignment"		"center"
		"Command"		"engine dodstudio_clear_decals"
		"tooltiptext"		"Clear every decal (bullet holes, blood, sprays)."
	}
	"GotoLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"GotoLabel"
		"xpos"		"296"
		"ypos"		"108"
		"wide"		"44"
		"tall"		"24"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"Go to"
		"textAlignment"		"east"
	}
	"GotoTime"
	{
		"ControlName"		"TextEntry"
		"fieldName"		"GotoTime"
		"xpos"		"344"
		"ypos"		"108"
		"wide"		"100"
		"tall"		"24"
		"visible"		"1"
		"enabled"		"1"
		"tooltiptext"		"A time to jump to: 20:33, 20:33:50 or seconds. Enter jumps."
	}
	"GotoButton"
	{
		"ControlName"		"Button"
		"fieldName"		"GotoButton"
		"xpos"		"448"
		"ypos"		"108"
		"wide"		"48"
		"tall"		"24"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"Go"
		"textAlignment"		"center"
		"Command"		"goto"
		"tooltiptext"		"Jump to the time in the box."
	}
	"Hint"
	{
		"ControlName"		"Label"
		"fieldName"		"Hint"
		"xpos"		"8"
		"ypos"		"142"
		"wide"		"488"
		"tall"		"24"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"Go to: 20:33, 20:33:50 or seconds, then Enter. Start a demo with viewdemo first."
		"textAlignment"		"west"
	}
	"EnablePlaybackButton"
	{
		"ControlName"		"Button"
		"fieldName"		"EnablePlaybackButton"
		"xpos"		"8"
		"ypos"		"172"
		"wide"		"400"
		"tall"		"24"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"Show the time and slider here (hides the VCR bar)"
		"textAlignment"		"center"
		"Command"		"engine dodstudio_viewdemo_in_panel 1"
		"tooltiptext"		"Turns on dodstudio_viewdemo_in_panel: this tab shows the time and slider, and the VCR bar hides."
	}
	"LoadLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"LoadLabel"
		"xpos"		"8"
		"ypos"		"200"
		"wide"		"180"
		"tall"		"22"
		"visible"		"0"
		"enabled"		"1"
		"labelText"		""
		"textAlignment"		"west"
		"tooltiptext"		"How much of the demo the demo player has read. It plays and seeks only as far as that."
	}
	"LoadProgress"
	{
		"ControlName"		"ProgressBar"
		"fieldName"		"LoadProgress"
		"xpos"		"196"
		"ypos"		"204"
		"wide"		"300"
		"tall"		"14"
		"visible"		"0"
		"enabled"		"1"
		"tooltiptext"		"How much of the demo the demo player has read. It plays and seeks only as far as that."
	}
}
