"dodstudio_ui/Review.res"
{
	"ReviewHeading"
	{
		"ControlName"		"Label"
		"fieldName"		"ReviewHeading"
		"xpos"		"8"
		"ypos"		"8"
		"wide"		"520"
		"tall"		"24"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"No review running."
		"textAlignment"		"west"
		"helptext"		"Which highlight this is, and how many are left to answer."
	}
	"ReviewDetail"
	{
		"ControlName"		"Label"
		"fieldName"		"ReviewDetail"
		"xpos"		"8"
		"ypos"		"34"
		"wide"		"520"
		"tall"		"24"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"In DoD Studio, tick demos in the Master Demo Queue and press Review highlights."
		"textAlignment"		"west"
		"helptext"		"Whose highlight it is, and what the review is doing."
	}
	"KillsLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"KillsLabel"
		"xpos"		"8"
		"ypos"		"66"
		"wide"		"60"
		"tall"		"24"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"Kills"
		"textAlignment"		"west"
		"helptext"		"The kill range to keep: from this kill to that one."
	}
	"ReviewFrom"
	{
		"ControlName"		"TextEntry"
		"fieldName"		"ReviewFrom"
		"xpos"		"72"
		"ypos"		"66"
		"wide"		"40"
		"tall"		"24"
		"visible"		"1"
		"enabled"		"1"
		"helptext"		"The first kill to keep, from 1."
	}
	"ToLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"ToLabel"
		"xpos"		"118"
		"ypos"		"66"
		"wide"		"20"
		"tall"		"24"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"to"
		"textAlignment"		"center"
		"helptext"		"The kill range to keep: from this kill to that one."
	}
	"ReviewTo"
	{
		"ControlName"		"TextEntry"
		"fieldName"		"ReviewTo"
		"xpos"		"144"
		"ypos"		"66"
		"wide"		"40"
		"tall"		"24"
		"visible"		"1"
		"enabled"		"1"
		"helptext"		"The last kill to keep."
	}
	"KillCount"
	{
		"ControlName"		"Label"
		"fieldName"		"KillCount"
		"xpos"		"190"
		"ypos"		"66"
		"wide"		"120"
		"tall"		"24"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		""
		"textAlignment"		"west"
		"helptext"		"How many kills the highlight has."
	}
	"NoteLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"NoteLabel"
		"xpos"		"8"
		"ypos"		"98"
		"wide"		"60"
		"tall"		"24"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"Note"
		"textAlignment"		"west"
		"helptext"		"A note for the Notes column."
	}
	"ReviewNote"
	{
		"ControlName"		"TextEntry"
		"fieldName"		"ReviewNote"
		"xpos"		"72"
		"ypos"		"98"
		"wide"		"456"
		"tall"		"24"
		"visible"		"1"
		"enabled"		"1"
		"helptext"		"A note for the Notes column. Yes or No saves it."
	}
	"YesButton"
	{
		"ControlName"		"Button"
		"fieldName"		"YesButton"
		"xpos"		"8"
		"ypos"		"134"
		"wide"		"80"
		"tall"		"24"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"Yes"
		"textAlignment"		"center"
		"Command"		"engine dodstudio_review yes"
		"helptext"		"Keep it: the row becomes Pending, with this kill range and note. Then the next highlight."
	}
	"NoButton"
	{
		"ControlName"		"Button"
		"fieldName"		"NoButton"
		"xpos"		"92"
		"ypos"		"134"
		"wide"		"80"
		"tall"		"24"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"No"
		"textAlignment"		"center"
		"Command"		"engine dodstudio_review no"
		"helptext"		"Not this one. The note is still saved. Then the next highlight."
	}
	"ReplayButton"
	{
		"ControlName"		"Button"
		"fieldName"		"ReplayButton"
		"xpos"		"184"
		"ypos"		"134"
		"wide"		"80"
		"tall"		"24"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"Replay"
		"textAlignment"		"center"
		"Command"		"engine dodstudio_review replay"
		"helptext"		"Watch this highlight again."
	}
	"BackButton"
	{
		"ControlName"		"Button"
		"fieldName"		"BackButton"
		"xpos"		"276"
		"ypos"		"134"
		"wide"		"80"
		"tall"		"24"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"Back"
		"textAlignment"		"center"
		"Command"		"engine dodstudio_review back"
		"helptext"		"The previous highlight, without answering this one."
	}
	"NextButton"
	{
		"ControlName"		"Button"
		"fieldName"		"NextButton"
		"xpos"		"360"
		"ypos"		"134"
		"wide"		"80"
		"tall"		"24"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"Skip"
		"textAlignment"		"center"
		"Command"		"engine dodstudio_review next"
		"helptext"		"The next highlight, without answering this one."
	}
	"StopButton"
	{
		"ControlName"		"Button"
		"fieldName"		"StopButton"
		"xpos"		"448"
		"ypos"		"134"
		"wide"		"80"
		"tall"		"24"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"Stop"
		"textAlignment"		"center"
		"Command"		"engine dodstudio_review stop"
		"helptext"		"End the review. Every answer so far is already in DoD Studio."
	}
	"ReviewHint"
	{
		"ControlName"		"Label"
		"fieldName"		"ReviewHint"
		"xpos"		"8"
		"ypos"		"170"
		"wide"		"520"
		"tall"		"24"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"Keys: bind a key to dodstudio_review yes, no, replay or next in the console."
		"textAlignment"		"west"
		"helptext"		"Bind keys so the mouse isn't needed."
	}
}
