"dodstudio_ui/Settings.res"
{
	"cvar_dodstudio_spec_match_pov"
	{
		"ControlName"		"CheckButton"
		"fieldName"		"cvar_dodstudio_spec_match_pov"
		"xpos"		"8"
		"ypos"		"6"
		"wide"		"256"
		"tall"		"22"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"Match the player's own view"
		"textAlignment"		"west"
	}
	"cvar_dodstudio_spec_lock"
	{
		"ControlName"		"CheckButton"
		"fieldName"		"cvar_dodstudio_spec_lock"
		"xpos"		"8"
		"ypos"		"30"
		"wide"		"256"
		"tall"		"22"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"Keep the camera on one player"
		"textAlignment"		"west"
	}
	"cvar_dodstudio_hide_spectator_bars"
	{
		"ControlName"		"CheckButton"
		"fieldName"		"cvar_dodstudio_hide_spectator_bars"
		"xpos"		"8"
		"ypos"		"54"
		"wide"		"256"
		"tall"		"22"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"Hide the spectator bars"
		"textAlignment"		"west"
	}
	"cvar_dodstudio_hide_hltv_messages"
	{
		"ControlName"		"CheckButton"
		"fieldName"		"cvar_dodstudio_hide_hltv_messages"
		"xpos"		"8"
		"ypos"		"78"
		"wide"		"256"
		"tall"		"22"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"Hide HLTV messages"
		"textAlignment"		"west"
	}
	"cvar_dodstudio_hide_scoreboard"
	{
		"ControlName"		"CheckButton"
		"fieldName"		"cvar_dodstudio_hide_scoreboard"
		"xpos"		"8"
		"ypos"		"102"
		"wide"		"256"
		"tall"		"22"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"Hide the scoreboard"
		"textAlignment"		"west"
	}
	"cvar_dodstudio_hide_crosshair"
	{
		"ControlName"		"CheckButton"
		"fieldName"		"cvar_dodstudio_hide_crosshair"
		"xpos"		"8"
		"ypos"		"126"
		"wide"		"256"
		"tall"		"22"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"Hide the crosshair"
		"textAlignment"		"west"
	}
	"cvar_dodstudio_hide_hand_signals"
	{
		"ControlName"		"CheckButton"
		"fieldName"		"cvar_dodstudio_hide_hand_signals"
		"xpos"		"8"
		"ypos"		"150"
		"wide"		"256"
		"tall"		"22"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"Hide hand signals"
		"textAlignment"		"west"
	}
	"cvar_dodstudio_mute_voice_commands"
	{
		"ControlName"		"CheckButton"
		"fieldName"		"cvar_dodstudio_mute_voice_commands"
		"xpos"		"8"
		"ypos"		"174"
		"wide"		"256"
		"tall"		"22"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"Mute voice commands"
		"textAlignment"		"west"
	}
	"cvar_dodstudio_hd_enabled"
	{
		"ControlName"		"CheckButton"
		"fieldName"		"cvar_dodstudio_hd_enabled"
		"xpos"		"8"
		"ypos"		"198"
		"wide"		"256"
		"tall"		"22"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"HD textures"
		"textAlignment"		"west"
	}
	"cvar_dodstudio_viewdemo_in_panel"
	{
		"ControlName"		"CheckButton"
		"fieldName"		"cvar_dodstudio_viewdemo_in_panel"
		"xpos"		"272"
		"ypos"		"6"
		"wide"		"256"
		"tall"		"22"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"viewdemo opens this window"
		"textAlignment"		"west"
	}
	"cvar_dodstudio_console_in_panel"
	{
		"ControlName"		"CheckButton"
		"fieldName"		"cvar_dodstudio_console_in_panel"
		"xpos"		"272"
		"ypos"		"30"
		"wide"		"256"
		"tall"		"22"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"The console key opens this window"
		"textAlignment"		"west"
	}
	"cvar_dodstudio_resizable_windows"
	{
		"ControlName"		"CheckButton"
		"fieldName"		"cvar_dodstudio_resizable_windows"
		"xpos"		"272"
		"ypos"		"54"
		"wide"		"256"
		"tall"		"22"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"Resizable windows"
		"textAlignment"		"west"
	}
	"cvar_dodstudio_remember_window_layout"
	{
		"ControlName"		"CheckButton"
		"fieldName"		"cvar_dodstudio_remember_window_layout"
		"xpos"		"272"
		"ypos"		"78"
		"wide"		"256"
		"tall"		"22"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"Remember where windows were"
		"textAlignment"		"west"
	}
	"cvar_dodstudio_seek_skip_between"
	{
		"ControlName"		"CheckButton"
		"fieldName"		"cvar_dodstudio_seek_skip_between"
		"xpos"		"272"
		"ypos"		"102"
		"wide"		"256"
		"tall"		"22"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"Seeking skips what it jumps over"
		"textAlignment"		"west"
	}
	"cvar_hud_draw"
	{
		"ControlName"		"CheckButton"
		"fieldName"		"cvar_hud_draw"
		"xpos"		"272"
		"ypos"		"126"
		"wide"		"256"
		"tall"		"22"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"Draw the HUD"
		"textAlignment"		"west"
	}
	"cvar_r_drawviewmodel"
	{
		"ControlName"		"CheckButton"
		"fieldName"		"cvar_r_drawviewmodel"
		"xpos"		"272"
		"ypos"		"150"
		"wide"		"256"
		"tall"		"22"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"Draw the gun"
		"textAlignment"		"west"
	}
	"ResetSettingsButton"
	{
		"ControlName"		"Button"
		"fieldName"		"ResetSettingsButton"
		"xpos"		"272"
		"ypos"		"198"
		"wide"		"200"
		"tall"		"24"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"Reset to defaults"
		"textAlignment"		"center"
		"Command"		"reset_settings"
	}
}
