"dodstudio_ui/Settings.res"
{
	"cvar_dodstudio_spec_match_pov"
	{
		"ControlName"		"CheckButton"
		"fieldName"		"cvar_dodstudio_spec_match_pov"
		"xpos"		"8"
		"ypos"		"6"
		"wide"		"256"
		"tall"		"22"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"Match the player's own view"
		"textAlignment"		"west"
		"tooltiptext"		"dodstudio_spec_match_pov: a spectated view looks like the player's own recording."
	}
	"cvar_dodstudio_spec_lock"
	{
		"ControlName"		"CheckButton"
		"fieldName"		"cvar_dodstudio_spec_lock"
		"xpos"		"8"
		"ypos"		"30"
		"wide"		"256"
		"tall"		"22"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"Keep the camera on one player"
		"textAlignment"		"west"
		"tooltiptext"		"dodstudio_spec_lock: the camera stays on the player when he dies."
	}
	"cvar_dodstudio_hide_spectator_bars"
	{
		"ControlName"		"CheckButton"
		"fieldName"		"cvar_dodstudio_hide_spectator_bars"
		"xpos"		"8"
		"ypos"		"54"
		"wide"		"256"
		"tall"		"22"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"Hide the spectator bars"
		"textAlignment"		"west"
		"tooltiptext"		"dodstudio_hide_spectator_bars: hide the spectator bars."
	}
	"cvar_dodstudio_hide_hltv_messages"
	{
		"ControlName"		"CheckButton"
		"fieldName"		"cvar_dodstudio_hide_hltv_messages"
		"xpos"		"8"
		"ypos"		"78"
		"wide"		"256"
		"tall"		"22"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"Hide HLTV messages"
		"textAlignment"		"west"
		"tooltiptext"		"dodstudio_hide_hltv_messages: hide the HLTV proxy's messages."
	}
	"cvar_dodstudio_hide_scoreboard"
	{
		"ControlName"		"CheckButton"
		"fieldName"		"cvar_dodstudio_hide_scoreboard"
		"xpos"		"8"
		"ypos"		"102"
		"wide"		"256"
		"tall"		"22"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"Hide the scoreboard"
		"textAlignment"		"west"
		"tooltiptext"		"dodstudio_hide_scoreboard: recorded TAB presses don't show the scoreboard."
	}
	"cvar_dodstudio_hide_crosshair"
	{
		"ControlName"		"CheckButton"
		"fieldName"		"cvar_dodstudio_hide_crosshair"
		"xpos"		"8"
		"ypos"		"126"
		"wide"		"256"
		"tall"		"22"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"Hide the crosshair"
		"textAlignment"		"west"
		"tooltiptext"		"dodstudio_hide_crosshair: hide the crosshair."
	}
	"cvar_dodstudio_hide_hand_signals"
	{
		"ControlName"		"CheckButton"
		"fieldName"		"cvar_dodstudio_hide_hand_signals"
		"xpos"		"8"
		"ypos"		"150"
		"wide"		"256"
		"tall"		"22"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"Hide hand signals"
		"textAlignment"		"west"
		"tooltiptext"		"dodstudio_hide_hand_signals: no hand-signal animations."
	}
	"cvar_dodstudio_mute_voice_commands"
	{
		"ControlName"		"CheckButton"
		"fieldName"		"cvar_dodstudio_mute_voice_commands"
		"xpos"		"8"
		"ypos"		"174"
		"wide"		"256"
		"tall"		"22"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"Mute voice commands"
		"textAlignment"		"west"
		"tooltiptext"		"dodstudio_mute_voice_commands: silence voice commands."
	}
	"cvar_dodstudio_hd_enabled"
	{
		"ControlName"		"CheckButton"
		"fieldName"		"cvar_dodstudio_hd_enabled"
		"xpos"		"8"
		"ypos"		"198"
		"wide"		"256"
		"tall"		"22"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"HD textures"
		"textAlignment"		"west"
		"tooltiptext"		"dodstudio_hd_enabled: HD textures (walls, detail and sky change from the next map)."
	}
	"cvar_dodstudio_viewdemo_in_panel"
	{
		"ControlName"		"CheckButton"
		"fieldName"		"cvar_dodstudio_viewdemo_in_panel"
		"xpos"		"272"
		"ypos"		"6"
		"wide"		"256"
		"tall"		"22"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"viewdemo opens this window"
		"textAlignment"		"west"
		"tooltiptext"		"dodstudio_viewdemo_in_panel: viewdemo opens this window instead of the VCR bar."
	}
	"cvar_dodstudio_console_in_panel"
	{
		"ControlName"		"CheckButton"
		"fieldName"		"cvar_dodstudio_console_in_panel"
		"xpos"		"272"
		"ypos"		"30"
		"wide"		"256"
		"tall"		"22"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"The console key opens this window"
		"textAlignment"		"west"
		"tooltiptext"		"dodstudio_console_in_panel: the console key opens this window's Console tab."
	}
	"cvar_dodstudio_resizable_windows"
	{
		"ControlName"		"CheckButton"
		"fieldName"		"cvar_dodstudio_resizable_windows"
		"xpos"		"272"
		"ypos"		"54"
		"wide"		"256"
		"tall"		"22"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"Resizable windows"
		"textAlignment"		"west"
		"tooltiptext"		"dodstudio_resizable_windows: every game window can be resized."
	}
	"cvar_dodstudio_remember_window_layout"
	{
		"ControlName"		"CheckButton"
		"fieldName"		"cvar_dodstudio_remember_window_layout"
		"xpos"		"272"
		"ypos"		"78"
		"wide"		"256"
		"tall"		"22"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"Remember where windows were"
		"textAlignment"		"west"
		"tooltiptext"		"dodstudio_remember_window_layout: game windows come back where you left them."
	}
	"cvar_dodstudio_seek_skip_between"
	{
		"ControlName"		"CheckButton"
		"fieldName"		"cvar_dodstudio_seek_skip_between"
		"xpos"		"272"
		"ypos"		"102"
		"wide"		"256"
		"tall"		"22"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"Seeking skips what it jumps over"
		"textAlignment"		"west"
		"tooltiptext"		"dodstudio_seek_skip_between: a jump skips the events it passes over."
	}
	"cvar_hud_draw"
	{
		"ControlName"		"CheckButton"
		"fieldName"		"cvar_hud_draw"
		"xpos"		"272"
		"ypos"		"126"
		"wide"		"256"
		"tall"		"22"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"Draw the HUD"
		"textAlignment"		"west"
		"tooltiptext"		"hud_draw: the game's HUD."
	}
	"cvar_r_drawviewmodel"
	{
		"ControlName"		"CheckButton"
		"fieldName"		"cvar_r_drawviewmodel"
		"xpos"		"272"
		"ypos"		"150"
		"wide"		"256"
		"tall"		"22"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"Draw the gun"
		"textAlignment"		"west"
		"tooltiptext"		"r_drawviewmodel: the gun in first person."
	}
	"ResetSettingsButton"
	{
		"ControlName"		"Button"
		"fieldName"		"ResetSettingsButton"
		"xpos"		"272"
		"ypos"		"198"
		"wide"		"200"
		"tall"		"24"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"Reset to defaults"
		"textAlignment"		"center"
		"Command"		"reset_settings"
		"tooltiptext"		"Put every setting changed here back to its default, and forget the saved values."
	}
}
